'use client';

import { useState, useEffect } from 'react';
import { codeToHtml } from 'shiki';

interface ComponentPreviewProps {
  children: React.ReactNode;
  code: string;
  title?: string;
}

export function ComponentPreview({
  children,
  code,
  title,
}: ComponentPreviewProps) {
  const [showCode, setShowCode] = useState(false);
  const [copied, setCopied] = useState(false);
  const [highlightedHTML, setHighlightedHTML] = useState<string | null>(null);

  useEffect(() => {
    if (!showCode) return;
    // Detect current color scheme to pick the right Shiki theme
    const isDark = document.documentElement.classList.contains('dark');
    const theme = isDark ? 'github-dark' : 'github-light';

    // Re-highlight when theme might have changed
    codeToHtml(code, { lang: 'tsx', theme }).then(setHighlightedHTML);
  }, [showCode, code]);

  async function handleCopy() {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div className="preview-container">
      <div className="preview-render" style={{ isolation: 'isolate', color: 'var(--text-primary)' }}>
        {children}
      </div>
      <div className="preview-footer">
        {title ? <p className="preview-title">{title}</p> : <span />}
        <div style={{ display: 'flex', gap: '0.5rem' }}>
          {showCode && (
            <button className="preview-copy" onClick={handleCopy}>
              {copied ? 'Copied!' : 'Copy'}
            </button>
          )}
          <button
            className="preview-toggle"
            onClick={() => setShowCode(!showCode)}
          >
            {showCode ? 'Hide Code' : 'Show Code'}
          </button>
        </div>
      </div>
      {showCode && (
        <div className="preview-code">
          {highlightedHTML ? (
            // Safe: highlightedHTML is generated by Shiki from static MDX code strings, not user input
            <div dangerouslySetInnerHTML={{ __html: highlightedHTML }} />
          ) : (
            <pre><code>{code}</code></pre>
          )}
        </div>
      )}
    </div>
  );
}
