/**
 * CSS Token Generator
 *
 * Reads token definitions from src/tokens/ and outputs:
 *   dist/tokens.css — all CSS custom properties organized by tier
 *   dist/primitives.css — primitive tokens only
 *   dist/semantic.css — semantic tokens only
 *   dist/themes/light.css — light theme adaptive tokens
 *   dist/themes/dark.css — dark theme adaptive tokens
 *   dist/index.css — full bundle (imports all above)
 */

import { writeFileSync, readFileSync, readdirSync, mkdirSync, existsSync } from "fs";
import { join, dirname, basename } from "path";
import { fileURLToPath } from "url";

import {
  primitiveColors,
  primitiveSpacing,
  primitiveRadius,
  primitiveBorderWidths,
  primitiveFontSizes,
  primitiveFontWeights,
  primitiveLineHeights,
  primitiveShadows,
  primitiveZIndex,
  primitiveFontFamilies,
  primitiveOverlay,
  primitiveFocusRing,
  primitiveMotionDurations,
  primitiveMotionEasings,
} from "../tokens/primitives.js";

import {
  semanticText,
  semanticSurface,
  semanticBorder,
  semanticInteractive,
  semanticSpacing,
  semanticTypography,
  semanticOverlay,
  semanticFocusRing,
  semanticShadow,
  semanticMotionDuration,
  semanticMotionEasing,
} from "../tokens/semantic.js";

import {
  adaptiveText,
  adaptiveSurface,
  adaptiveBorder,
  adaptiveInteractive,
} from "../tokens/adaptive.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST_DIR = join(__dirname, "../../dist");
const THEMES_DIR = join(DIST_DIR, "themes");

// ============================================================
// Helpers
// ============================================================

function ensureDirs(): void {
  if (!existsSync(DIST_DIR)) mkdirSync(DIST_DIR, { recursive: true });
  if (!existsSync(THEMES_DIR)) mkdirSync(THEMES_DIR, { recursive: true });
}

function header(label: string): string {
  return [
    "/* ============================================",
    `   ${label}`,
    "   Generated by @loworbitstudio/visor-core",
    "   DO NOT EDIT — run `npm run build` to regenerate",
    "   ============================================ */",
    "",
  ].join("\n");
}

function sectionComment(label: string): string {
  return `\n/* --- ${label} --- */`;
}

/** Wrap lines in a CSS rule block */
function block(selector: string, declarations: string[]): string {
  if (declarations.length === 0) return "";
  return [selector + " {", ...declarations.map((d) => `  ${d}`), "}", ""].join(
    "\n"
  );
}

/** Scale values are authored in px; the CSS uses relative units (16px base). */
const BASE_PX = 16;

function toRelative(px: number, unit: "rem" | "em"): string {
  return px === 0 ? "0" : `${px / BASE_PX}${unit}`;
}

/**
 * Fluid type: full size from the desktop breakpoint up, scaling down linearly
 * to 7/8 of the size at the smallest supported viewport.
 */
const FLUID_MIN_VIEWPORT = 390;
const FLUID_MAX_VIEWPORT = 1440;
const FLUID_MIN_SCALE = 0.875;

function toFluid(px: number): string {
  const minPx = px * FLUID_MIN_SCALE;
  const slope = (px - minPx) / (FLUID_MAX_VIEWPORT - FLUID_MIN_VIEWPORT);
  const intercept = minPx - slope * FLUID_MIN_VIEWPORT;
  const round = (n: number) => Number(n.toFixed(4));
  return `clamp(${round(minPx / BASE_PX)}rem, ${round(intercept / BASE_PX)}rem + ${round(slope * 100)}vw, ${px / BASE_PX}rem)`;
}

/** Convert a token name reference like "color-gray-900" to "var(--color-gray-900)" */
function toVar(ref: string): string {
  return `var(--${ref})`;
}

// ============================================================
// Primitive CSS generation
// ============================================================

function generatePrimitivesCSS(): string {
  const lines: string[] = [];

  // Colors
  lines.push(sectionComment("Primitive: Colors"));
  const colorDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveColors)) {
    colorDecls.push(`--color-${name}: ${value};`);
  }
  lines.push(block(":root", colorDecls));

  // Spacing
  lines.push(sectionComment("Primitive: Spacing"));
  const spacingDecls: string[] = [];
  for (const [name, px] of Object.entries(primitiveSpacing)) {
    spacingDecls.push(`--spacing-${name}: ${toRelative(px, "em")}; /* ${px}px */`);
  }
  lines.push(block(":root", spacingDecls));

  // Border Radius
  lines.push(sectionComment("Primitive: Border Radius"));
  const radiusDecls: string[] = [];
  for (const [name, px] of Object.entries(primitiveRadius)) {
    if (px >= 9999) {
      radiusDecls.push(`--radius-${name}: 9999px;`);
    } else if (px === 0) {
      radiusDecls.push(`--radius-${name}: 0;`);
    } else {
      radiusDecls.push(`--radius-${name}: ${toRelative(px, "em")}; /* ${px}px */`);
    }
  }
  lines.push(block(":root", radiusDecls));

  // Border Widths
  lines.push(sectionComment("Primitive: Border Widths"));
  const borderWidthDecls: string[] = [];
  for (const [name, px] of Object.entries(primitiveBorderWidths)) {
    borderWidthDecls.push(`--border-width-${name}: ${px}px;`);
  }
  lines.push(block(":root", borderWidthDecls));

  // Font Families
  lines.push(sectionComment("Primitive: Font Families"));
  const fontFamilyDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveFontFamilies)) {
    fontFamilyDecls.push(`--font-${name}: ${value};`);
  }
  lines.push(block(":root", fontFamilyDecls));

  // Font Sizes
  lines.push(sectionComment("Primitive: Font Sizes"));
  const fontSizeDecls: string[] = [];
  for (const [name, px] of Object.entries(primitiveFontSizes)) {
    fontSizeDecls.push(`--font-size-${name}: ${toFluid(px)}; /* ${px}px */`);
  }
  lines.push(block(":root", fontSizeDecls));

  // Font Weights
  lines.push(sectionComment("Primitive: Font Weights"));
  const fontWeightDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveFontWeights)) {
    fontWeightDecls.push(`--font-weight-${name}: ${value};`);
  }
  lines.push(block(":root", fontWeightDecls));

  // Line Heights
  lines.push(sectionComment("Primitive: Line Heights"));
  const lineHeightDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveLineHeights)) {
    lineHeightDecls.push(`--line-height-${name}: ${value};`);
  }
  lines.push(block(":root", lineHeightDecls));

  // Shadows
  lines.push(sectionComment("Primitive: Shadows"));
  const shadowDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveShadows)) {
    shadowDecls.push(`--shadow-${name}: ${value};`);
  }
  lines.push(block(":root", shadowDecls));

  // Z-index
  lines.push(sectionComment("Primitive: Z-Index"));
  const zIndexDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveZIndex)) {
    zIndexDecls.push(`--z-${name}: ${value};`);
  }
  lines.push(block(":root", zIndexDecls));

  // Overlay
  lines.push(sectionComment("Primitive: Overlay"));
  const overlayDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveOverlay)) {
    overlayDecls.push(`--overlay-${name}: ${value};`);
  }
  lines.push(block(":root", overlayDecls));

  // Focus Ring
  lines.push(sectionComment("Primitive: Focus Ring"));
  const focusRingDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveFocusRing)) {
    focusRingDecls.push(`--focus-ring-${name}: ${value};`);
  }
  lines.push(block(":root", focusRingDecls));

  // Motion Durations
  lines.push(sectionComment("Primitive: Motion Durations"));
  const motionDurationDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveMotionDurations)) {
    motionDurationDecls.push(`--motion-duration-${name}: ${value};`);
  }
  lines.push(block(":root", motionDurationDecls));

  // Motion Easings
  lines.push(sectionComment("Primitive: Motion Easings"));
  const motionEasingDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveMotionEasings)) {
    motionEasingDecls.push(`--motion-easing-${name}: ${value};`);
  }
  lines.push(block(":root", motionEasingDecls));

  return header("Visor Design Tokens — Primitives") + lines.join("\n");
}

// ============================================================
// Semantic CSS generation
// ============================================================

function generateSemanticCSS(): string {
  const lines: string[] = [];

  // Text
  lines.push(sectionComment("Semantic: Text"));
  const textDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticText)) {
    textDecls.push(`--text-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", textDecls));

  // Surface
  lines.push(sectionComment("Semantic: Surface"));
  const surfaceDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticSurface)) {
    surfaceDecls.push(`--surface-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", surfaceDecls));

  // Border
  lines.push(sectionComment("Semantic: Border"));
  const borderDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticBorder)) {
    borderDecls.push(`--border-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", borderDecls));

  // Interactive
  lines.push(sectionComment("Semantic: Interactive"));
  const interactiveDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticInteractive)) {
    interactiveDecls.push(`--interactive-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", interactiveDecls));

  // Spacing
  lines.push(sectionComment("Semantic: Spacing"));
  const spacingDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticSpacing)) {
    spacingDecls.push(`--${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", spacingDecls));

  // Typography
  lines.push(sectionComment("Semantic: Typography"));
  const typographyDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticTypography)) {
    typographyDecls.push(`--${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", typographyDecls));

  // Motion Duration
  lines.push(sectionComment("Semantic: Motion Duration"));
  const motionDurationDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticMotionDuration)) {
    motionDurationDecls.push(`--motion-duration-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", motionDurationDecls));

  // Motion Easing
  lines.push(sectionComment("Semantic: Motion Easing"));
  const motionEasingDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticMotionEasing)) {
    motionEasingDecls.push(`--motion-easing-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", motionEasingDecls));

  // Overlay
  lines.push(sectionComment("Semantic: Overlay"));
  const overlaySemanticDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticOverlay)) {
    overlaySemanticDecls.push(`--overlay-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", overlaySemanticDecls));

  // Focus Ring
  lines.push(sectionComment("Semantic: Focus Ring"));
  const focusRingSemanticDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticFocusRing)) {
    focusRingSemanticDecls.push(`--focus-ring-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", focusRingSemanticDecls));

  // Shadows
  lines.push(sectionComment("Semantic: Shadow"));
  const shadowSemanticDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticShadow)) {
    shadowSemanticDecls.push(`--shadow-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", shadowSemanticDecls));

  return header("Visor Design Tokens — Semantic") + lines.join("\n");
}

// ============================================================
// Adaptive (theme) CSS generation
// ============================================================

/** Build adaptive token declarations for a given theme variant */
function buildAdaptiveDecls(theme: "light" | "dark"): {
  textDecls: string[];
  surfaceDecls: string[];
  borderDecls: string[];
  interactiveDecls: string[];
} {
  const textDecls: string[] = [];
  for (const [name, values] of Object.entries(adaptiveText)) {
    textDecls.push(`--text-${name}: ${toVar(values[theme])};`);
  }

  const surfaceDecls: string[] = [];
  for (const [name, values] of Object.entries(adaptiveSurface)) {
    surfaceDecls.push(`--surface-${name}: ${toVar(values[theme])};`);
  }

  const borderDecls: string[] = [];
  for (const [name, values] of Object.entries(adaptiveBorder)) {
    borderDecls.push(`--border-${name}: ${toVar(values[theme])};`);
  }

  const interactiveDecls: string[] = [];
  for (const [name, values] of Object.entries(adaptiveInteractive)) {
    interactiveDecls.push(`--interactive-${name}: ${toVar(values[theme])};`);
  }

  return { textDecls, surfaceDecls, borderDecls, interactiveDecls };
}

function generateThemeCSS(theme: "light" | "dark"): string {
  const themeLabel = theme === "light" ? "Light Theme" : "Dark Theme";
  const lines: string[] = [];
  const { textDecls, surfaceDecls, borderDecls, interactiveDecls } = buildAdaptiveDecls(theme);

  if (theme === "light") {
    // Light theme: applied to :root (default)
    lines.push(sectionComment("Adaptive: Text (light)"));
    lines.push(block(":root", textDecls));

    lines.push(sectionComment("Adaptive: Surface (light)"));
    lines.push(block(":root", surfaceDecls));

    lines.push(sectionComment("Adaptive: Border (light)"));
    lines.push(block(":root", borderDecls));

    lines.push(sectionComment("Adaptive: Interactive (light)"));
    lines.push(block(":root", interactiveDecls));
  } else {
    // Dark theme: applied to manual selectors
    const darkSelectors = [
      ".dark",
      ".theme-dark",
      '[data-theme="dark"]',
    ];
    const darkSelector = darkSelectors.join(",\n");

    lines.push(sectionComment("Adaptive: Text (dark) — manual toggle"));
    lines.push(block(darkSelector, textDecls));

    lines.push(sectionComment("Adaptive: Surface (dark) — manual toggle"));
    lines.push(block(darkSelector, surfaceDecls));

    lines.push(sectionComment("Adaptive: Border (dark) — manual toggle"));
    lines.push(block(darkSelector, borderDecls));

    lines.push(sectionComment("Adaptive: Interactive (dark) — manual toggle"));
    lines.push(block(darkSelector, interactiveDecls));

    // prefers-color-scheme: dark — auto detection
    lines.push(sectionComment("Adaptive: Text (dark) — prefers-color-scheme"));
    lines.push(
      `@media (prefers-color-scheme: dark) {\n${block(":root:not(.light):not(.theme-light):not([data-theme=\"light\"])", textDecls)}}`
    );
    lines.push("");

    lines.push(sectionComment("Adaptive: Surface (dark) — prefers-color-scheme"));
    lines.push(
      `@media (prefers-color-scheme: dark) {\n${block(":root:not(.light):not(.theme-light):not([data-theme=\"light\"])", surfaceDecls)}}`
    );
    lines.push("");

    lines.push(sectionComment("Adaptive: Border (dark) — prefers-color-scheme"));
    lines.push(
      `@media (prefers-color-scheme: dark) {\n${block(":root:not(.light):not(.theme-light):not([data-theme=\"light\"])", borderDecls)}}`
    );
    lines.push("");

    lines.push(sectionComment("Adaptive: Interactive (dark) — prefers-color-scheme"));
    lines.push(
      `@media (prefers-color-scheme: dark) {\n${block(":root:not(.light):not(.theme-light):not([data-theme=\"light\"])", interactiveDecls)}}`
    );
    lines.push("");
  }

  return header(`Visor Design Tokens — ${themeLabel}`) + lines.join("\n");
}

// ============================================================
// Full bundle (tokens.css)
// ============================================================

function generateTokensCSS(): string {
  const lines: string[] = [
    header("Visor Design Tokens — Full Bundle"),
    "/* Import order: primitives → semantic → adaptive */",
    "",
    "/* ============================================",
    "   Tier 1: Primitives",
    "   ============================================ */",
  ];

  // Primitives inlined
  const primitivesContent = generatePrimitivesCSS();
  // Strip the header from the primitives content (first 6 lines are header)
  const primitivesBody = primitivesContent
    .split("\n")
    .slice(6)
    .join("\n");
  lines.push(primitivesBody);

  lines.push(
    "/* ============================================",
    "   Tier 2: Semantic",
    "   ============================================ */"
  );
  const semanticContent = generateSemanticCSS();
  const semanticBody = semanticContent.split("\n").slice(6).join("\n");
  lines.push(semanticBody);

  // Tier 3: inline every theme file written to dist/themes (sorted for stable output)
  const themeFiles = readdirSync(THEMES_DIR)
    .filter((file) => file.endsWith(".css"))
    .sort();
  for (const file of themeFiles) {
    const theme = basename(file, ".css");
    lines.push(
      "/* ============================================",
      `   Tier 3: Adaptive — ${theme} theme (themes/${file})`,
      "   ============================================ */"
    );
    const themeContent = readFileSync(join(THEMES_DIR, file), "utf-8");
    lines.push(themeContent.split("\n").slice(6).join("\n"));
  }

  return lines.join("\n");
}

// ============================================================
// Index CSS (entry point)
// ============================================================

function generateIndexCSS(): string {
  return [
    header("Visor Design Tokens — Index"),
    "/* Full design token bundle */",
    "@import './tokens.css';",
    "",
  ].join("\n");
}

// ============================================================
// Main
// ============================================================

function main(): void {
  console.log("Generating Visor design tokens...\n");

  ensureDirs();

  // Generate primitives.css
  const primitivesCSS = generatePrimitivesCSS();
  writeFileSync(join(DIST_DIR, "primitives.css"), primitivesCSS, "utf-8");
  console.log("✓ dist/primitives.css");

  // Generate semantic.css
  const semanticCSS = generateSemanticCSS();
  writeFileSync(join(DIST_DIR, "semantic.css"), semanticCSS, "utf-8");
  console.log("✓ dist/semantic.css");

  // Generate light theme
  const lightCSS = generateThemeCSS("light");
  writeFileSync(join(THEMES_DIR, "light.css"), lightCSS, "utf-8");
  console.log("✓ dist/themes/light.css");

  // Generate dark theme
  const darkCSS = generateThemeCSS("dark");
  writeFileSync(join(THEMES_DIR, "dark.css"), darkCSS, "utf-8");
  console.log("✓ dist/themes/dark.css");

  // Generate full bundle
  const tokensCSS = generateTokensCSS();
  writeFileSync(join(DIST_DIR, "tokens.css"), tokensCSS, "utf-8");
  console.log("✓ dist/tokens.css");

  // Generate index.css entry point
  const indexCSS = generateIndexCSS();
  writeFileSync(join(DIST_DIR, "index.css"), indexCSS, "utf-8");
  console.log("✓ dist/index.css");

  console.log("\nToken counts:");
  console.log(
    `  Primitive colors: ${Object.keys(primitiveColors).length}`
  );
  console.log(`  Spacing steps: ${Object.keys(primitiveSpacing).length}`);
  console.log(`  Radius steps: ${Object.keys(primitiveRadius).length}`);
  console.log(`  Shadow steps: ${Object.keys(primitiveShadows).length}`);
  console.log(`  Motion durations: ${Object.keys(primitiveMotionDurations).length}`);
  console.log(`  Motion easings: ${Object.keys(primitiveMotionEasings).length}`);
  console.log(
    `  Semantic text: ${Object.keys(semanticText).length}`
  );
  console.log(
    `  Semantic surface: ${Object.keys(semanticSurface).length}`
  );
  console.log(
    `  Semantic border: ${Object.keys(semanticBorder).length}`
  );
  console.log(
    `  Semantic motion duration: ${Object.keys(semanticMotionDuration).length}`
  );
  console.log(
    `  Semantic motion easing: ${Object.keys(semanticMotionEasing).length}`
  );
  console.log(
    `  Semantic shadow: ${Object.keys(semanticShadow).length}`
  );
  console.log(
    `  Adaptive text: ${Object.keys(adaptiveText).length} (light + dark)`
  );
  console.log(
    `  Adaptive surface: ${Object.keys(adaptiveSurface).length} (light + dark)`
  );
  console.log(
    `  Adaptive border: ${Object.keys(adaptiveBorder).length} (light + dark)`
  );
  console.log(
    `  Adaptive interactive: ${Object.keys(adaptiveInteractive).length} (light + dark)`
  );

  console.log("\n✓ Token generation complete");
}

main();
